//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;

namespace StackExchange.Redis.Resilience
{
    using System.Threading.Tasks;
    using System.Threading;
    public partial interface IResilientConnectionMultiplexer : IConnectionMultiplexer
    {

        /// <summary>
        /// Tries to reconnect.
        /// </summary>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
        /// <returns>Whether the reconnect was successful.</returns>
        Task<bool> TryReconnectAsync(CancellationToken cancellationToken = default(CancellationToken));
    }
}
