<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Product>StackExchange.Redis.Resilience</Product>
    <Title>StackExchange.Redis.Resilience</Title>
    <Version>2.13.17</Version>
    <Authors>maca88</Authors>
    <Company />
    <Description>Provides a solution to force reconnect when StackExchange.Redis fails to reconnect after a connection blip.</Description>
    <TargetFrameworks>net461;netstandard2.0;net472;net6.0;net8.0;net10.0</TargetFrameworks>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/maca88/StackExchange.Redis.Resilience</PackageProjectUrl>
    <PackageTags>redis; resilience</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <TreatSpecificWarningsAsErrors />
    <LangVersion>8.0</LangVersion>
    <NoWarn>SER001;SER002;SER003;SER006</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
  </ItemGroup>
</Project>
